"""
SAT Centre Updater - Exporter Module    Generates summary reports in Markdown and HTML formats.
    CSV reports (changes, duplicates, failed) are generated by validator.py and updater.py.

Usage:
    from processing.exporter import ReportExporter

    exporter = ReportExporter()
    exporter.generate_summary(geocode_results, validation_summary, update_summary)
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

from config import settings

logger = logging.getLogger(__name__)


@dataclass
class PipelineStats:
    """Aggregate statistics for the full pipeline run."""

    start_time: datetime = field(default_factory=datetime.now)
    end_time: Optional[datetime] = None
    curl_parsed: bool = False
    download_status: int = 0
    download_format: str = "unknown"
    download_size: int = 0
    raw_file_path: str = ""
    total_centres: int = 0
    new_centres: int = 0
    updated_centres: int = 0
    removed_centres: int = 0
    failed_centres: int = 0
    geocoded_centres: int = 0
    cache_hits: int = 0
    api_calls: int = 0
    provider_usage: Dict[str, int] = field(default_factory=dict)
    validation_summary: Dict[str, Any] = field(default_factory=dict)

    @property
    def runtime_seconds(self) -> float:
        """Calculate total runtime."""
        if self.end_time:
            return (self.end_time - self.start_time).total_seconds()
        return 0.0

    @property
    def runtime_str(self) -> str:
        """Human-readable runtime string."""
        seconds = self.runtime_seconds
        if seconds < 60:
            return f"{seconds:.1f}s"
        minutes = int(seconds // 60)
        secs = seconds % 60
        return f"{minutes}m {secs:.1f}s"


class ReportExporter:
    """
    Generates pipeline reports in multiple formats.

    Outputs:
    - summary.md   (Markdown report)
    - summary.html (HTML report)
    """

    def __init__(self, reports_dir: Optional[Path] = None) -> None:
        """
        Initialize the exporter.

        Args:
            reports_dir: Directory for reports. Defaults to config setting.
        """
        self.reports_dir = reports_dir or settings.PATHS.REPORTS_DIR
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def generate_all(self, stats: PipelineStats) -> Dict[str, Path]:
        """
        Generate all report files.

        Args:
            stats: PipelineStats with all pipeline information.

        Returns:
            Dictionary mapping report name to file path.
        """
        results: Dict[str, Path] = {}

        results["summary_md"] = self._generate_summary_md(stats)
        results["summary_html"] = self._generate_summary_html(stats)

        logger.info(f"Reports generated in {self.reports_dir}")
        return results

    def _generate_summary_md(self, stats: PipelineStats) -> Path:
        """Generate a Markdown summary report."""
        file_path = self.reports_dir / "summary.md"

        provider_lines = (
            "\n".join(
                f"  - **{name}**: {count} calls"
                for name, count in stats.provider_usage.items()
                if count > 0
            )
            or "  - No provider calls"
        )

        content = f"""# SAT Centre Update Report

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Pipeline Summary

| Metric | Value |
|--------|-------|
| Runtime | {stats.runtime_str} |
| Download Status | HTTP {stats.download_status} |
| Response Format | {stats.download_format} |
| Download Size | {stats.download_size:,} bytes |
| Raw File | {stats.raw_file_path} |

## Centre Statistics

| Metric | Count |
|--------|-------|
| Total Centres | {stats.total_centres} |
| New Centres | {stats.new_centres} |
| Updated Centres | {stats.updated_centres} |
| Removed Centres | {stats.removed_centres} |
| Failed Centres | {stats.failed_centres} |
| Geocoded Centres | {stats.geocoded_centres} |

## API Usage

| Metric | Count |
|--------|-------|
| Cache Hits | {stats.cache_hits} |
| API Calls | {stats.api_calls} |

### Provider Usage

{provider_lines}

## Validation

| Check | Result |
|-------|--------|
"""

        for check, value in stats.validation_summary.items():
            content += f"| {check} | {value} |\n"

        file_path.write_text(content, encoding="utf-8")
        return file_path

    def _generate_summary_html(self, stats: PipelineStats) -> Path:
        """Generate an HTML summary report."""
        file_path = self.reports_dir / "summary.html"

        provider_rows = (
            "\n".join(
                f"<tr><td>{name}</td><td>{count}</td></tr>"
                for name, count in stats.provider_usage.items()
                if count > 0
            )
            or "<tr><td colspan='2'>No provider calls</td></tr>"
        )

        validation_rows = (
            "\n".join(
                f"<tr><td>{check}</td><td>{value}</td></tr>"
                for check, value in stats.validation_summary.items()
            )
            or "<tr><td colspan='2'>No validation data</td></tr>"
        )

        content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAT Centre Update Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #333; }}
        h1 {{ color: #1a1a2e; border-bottom: 2px solid #e94560; padding-bottom: 10px; }}
        h2 {{ color: #16213e; margin-top: 30px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 10px 15px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #f8f9fa; font-weight: 600; }}
        tr:hover {{ background-color: #f5f5f5; }}
        .stat-card {{ display: inline-block; background: #f8f9fa; border-radius: 8px; padding: 15px 25px; margin: 5px; text-align: center; }}
        .stat-value {{ font-size: 24px; font-weight: 700; color: #e94560; }}
        .stat-label {{ font-size: 12px; color: #666; text-transform: uppercase; }}
        footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>SAT Centre Update Report</h1>
    <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

    <div class="stat-card">
        <div class="stat-value">{stats.total_centres}</div>
        <div class="stat-label">Total Centres</div>
    </div>
    <div class="stat-card">
        <div class="stat-value">{stats.new_centres}</div>
        <div class="stat-label">New</div>
    </div>
    <div class="stat-card">
        <div class="stat-value">{stats.updated_centres}</div>
        <div class="stat-label">Updated</div>
    </div>
    <div class="stat-card">
        <div class="stat-value">{stats.failed_centres}</div>
        <div class="stat-label">Failed</div>
    </div>

    <h2>Pipeline Summary</h2>
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        <tr><td>Runtime</td><td>{stats.runtime_str}</td></tr>
        <tr><td>Download Status</td><td>HTTP {stats.download_status}</td></tr>
        <tr><td>Response Format</td><td>{stats.download_format}</td></tr>
        <tr><td>Download Size</td><td>{stats.download_size:,} bytes</td></tr>
    </table>

    <h2>API Usage</h2>
    <table>
        <tr><th>Metric</th><th>Count</th></tr>
        <tr><td>Cache Hits</td><td>{stats.cache_hits}</td></tr>
        <tr><td>API Calls</td><td>{stats.api_calls}</td></tr>
    </table>

    <h2>Provider Usage</h2>
    <table>
        <tr><th>Provider</th><th>Calls</th></tr>
        {provider_rows}
    </table>

    <h2>Validation</h2>
    <table>
        <tr><th>Check</th><th>Result</th></tr>
        {validation_rows}
    </table>

    <footer>
        SAT Centre Updater &mdash; Generated by the SAT Centre Updater pipeline
    </footer>
</body>
</html>"""

        file_path.write_text(content, encoding="utf-8")
        return file_path
